### ISSUE TITLE
kick {run, test} to run specified project

### ISSUE THREAD

**Issue by GrayJack** [juliangaal/kick#19]
Suggestion, add `kick run` and `kick test` to run and run tests.

I'm thinking in add a config file inside all projects created with kick, maybe a toml, to specify what to run when run these subcommands

**Comment by juliangaal** [comment]
I'm not sure if this would be the proper scope for kick. Why don't use existing tools for that, e.g. `make test` in a CMake based project with `enable_testing()` set in CMakeLists.txt?

**Comment by GrayJack** [comment]
Maybe, I was just thinking that cargo, stack and leiningen that at first were created to structure projects, also have these options.

**Comment by juliangaal** [comment]
while true, they are build tools. Kick is really only meant to get your started, after which language specific tools should take over.
